### PR TITLE
GitKraken plugin

### PR DESCRIPTION
**Pull request by delphiki**
It's only missing the icon, and I don't know if there are any dependencies required, but it should be working out of the box.

### CODE REVIEW

**Comment by Abhinav1217** [comment]
You can put the icon inside the plugin folder. Fedy will first search for the icon in the icon theme, if it's not found, it'll search in the plugin folder for svg and png formats. You need to specify the icon name in the metadata.json file. 

Try it and let me know if you have any problem adding icon.

**Comment by delphiki** [comment]
I thought about it, but had a look at all the other plugins and saw no extra files (only install/uninstall/metadata), so I wondered it that was intentional or not to keep it this way.

But I'll add the icon this way, thanks!

**Comment by delphiki** [comment]
I add to use a cp command instead of xdg-icon-resource, because sadly xdg does not support svg (scalable), but it now have a pretty icon.

**Comment by Abhinav1217** [comment]
I will test this on various spins. If we see any issue, we will notify you. Thanks for the plugin.

**Comment by delphiki** [comment]
Thanks for the review.

**Pull request merged**
